mysql:
 host: "localhost"
 port: "3306"
 user: "root"
 password: "rootmysql"
 db: "northernstar"
 
 
postgresql:
  url: "jdbc:postgresql://localhost:5432/northernstar"
  driver_name: "org.postgresql.Driver"
  user: "postgres"
  password: "postgres"
  
  
  